name: My First Pipeline
on:
  push:

jobs:
  test:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v4
      - name: Test
        run: echo "Hello Dheerendra Verma"
        run: echo "I am from Gwalior"
        run: echo "My job role is DevOps Engineer"


