name: My First Pipeline
on:
  push:

jobs:
  test:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Hello Dheerendra"
        run: echo "I am DevOps Engineer"
        run: echo "I am looking for an apportunity where i can contribute my skills"
