name: My First Pipeline

on:
  push:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Hello Dheerendra"
          echo "I am DevOps Engineer"
          echo "I am looking for an opportunity where I can contribute my skills"
